{
 "title": "kubernetes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Number of Namespace Created",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_namespace_created{namespace=~\"ns1|ns2|ns3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Pods Created",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{pod=~\"myapp-5c64cc964b-4vz6m|myapp-5c64cc964b-5ndhp|myapp-5c64cc964b-5pzfg|myapp-5c64cc964b-6wdc4|myapp-5c64cc964b-8dxbs|myapp-5c64cc964b-9cb6t|myapp-5c64cc964b-g5jsw|myapp-5c64cc964b-ggzt5|myapp-5c64cc964b-hh4dr|myapp-5c64cc964b-jqcz9|myapp-5c64cc964b-nkvs6|myapp-5c64cc964b-tj6kq\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (namespace, pod, phase) (kube_pod_status_phase{namespace=\"ns1\"})\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by (namespace, pod, phase) (kube_pod_status_phase{namespace=\"ns2\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum by (namespace, pod, phase) (kube_pod_status_phase{namespace=\"ns3\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Container Info ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kube_pod_container_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Services Uptime",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  }
 ]
}